# This workflow creates docker images that are then used for:
#
# - Root-project packages CI
# 
# All created images are then uploaded to GitHub Container registry

name: Create images

# Images to build are
# - arch
# - centos7
# - conda
# - fedora
# - gentoo
# - ubuntu

on:
  push:
    branches:
      - master
  schedule:
    # every Sunday
    - cron:  '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        image: ["arch", "centos7", "conda", "fedora", "ubuntu"]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Link image to repository by appending a label to Dockerfile
        run: |
          sudo chmod 777 ${{ matrix.image }}/Dockerfile &&
          sed -i "/^FROM.*/a LABEL org.opencontainers.image.source https://github.com/${{ github.repository }}" ${{ matrix.image }}/Dockerfile &&
          cat ${{ matrix.image }}/Dockerfile

      - name: Build the docker image
        run: |
          docker build -t ${{ matrix.image }} ${{ matrix.image }}/

      - name: Tag the docker image
        run: |
          docker tag ${{ matrix.image }} ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
        
      - name: Publish image
        env:
          deploy_secret: ${{ secrets.CR_PAT }}
        run: |
          if [ ! -z ${deploy_secret} ]; then
            echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin;
            docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest;
          else
            echo "Skipping deploy no secrets present";
          fi

